name: Brier Law Firm
favicon: null
layout_spectrum: 0.6551353316754103
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c5c6c0'
    - '#30312b'
    - '#020300'
    - '#958c6f'
  brandStrength: 1
  lightness: 0.5955241846386343
  saturation: 0.3570958359632641
  rhythmicContrast: 0.4276985256001353
purpose: []
